{
  "hash": "2c524ba86ce44313dbd455a85319cc09",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Temperature and SEU Sensitivity: EU-Prompt Variation\"\nsubtitle: \"Application Report: Temperature Study 3\"\ndescription: |\n  Tests whether explicitly instructing the LLM to maximize expected utility\n  increases estimated sensitivity (α) compared to the base temperature study.\n  Uses the same problems, assessments, and embeddings — only the choice prompt\n  is modified to include an explicit EU-maximization instruction.\ncategories: [applications, temperature, m_01, eu-prompt]\nexecute:\n  cache: true\n---\n\n\n## Introduction\n\nThe [initial temperature study](../temperature_study/01_initial_study.qmd) established\nthat higher LLM sampling temperature systematically reduces estimated sensitivity (α)\nto subjective expected utility maximization. The global slope was Δα/ΔT ≈ −25, with\nstrong pairwise separation at the extremes (T=0.0 vs T≥1.0) and near-equality at\nmoderate levels (T=0.3 ≈ T=0.7).\n\nThis study asks a complementary question: **does explicitly telling the LLM to maximize\nexpected utility increase α?**\n\nThe intervention is minimal. The choice prompt is identical to the base study except for\none added paragraph:\n\n> *Select the claim that maximizes your expected utility with respect to the three\n> outcomes above. For each claim, consider the subjective probability you assign to\n> each outcome and your utility for that outcome. Choose the claim for which the\n> probability-weighted utility across the three outcomes is highest.*\n\nEverything else is held constant:\n\n- Same 100 problems × 3 presentations\n- Same assessment texts (reused from the base study, not re-collected)\n- Same PCA-reduced embeddings\n- Same model: m_01 with Lognormal(3.0, 0.75) prior on α\n- Same 5 temperature levels: 0.0, 0.3, 0.7, 1.0, 1.5\n\nThis design isolates the prompt intervention to the **decision rule** while holding\n**belief formation** (assessments) constant — a clean decomposition of the two stages\nof SEU.\n\n## Experimental Design\n\n### Prompt Modification\n\nThe base study's choice prompt presents three outcomes and asks the LLM to select a\nclaim. The EU-prompt variant adds an explicit instruction to maximize expected utility\nwith respect to those outcomes — referencing subjective probabilities, utilities, and\nprobability-weighted utility.\n\nThe assessment prompt is not modified. Assessments are reused directly from the base\nstudy, ensuring that the feature representation (w vectors) is identical.\n\n### Data Reuse\n\n| Component | Base Study | EU-Prompt Study |\n|-----------|-----------|-----------------|\n| Problems | Generated | **Reused** |\n| Assessments | Collected | **Reused** |\n| Embeddings | Computed | **Reused** |\n| Choices | Collected | **New** (EU prompt) |\n| Model fitting | m_01 | m_01 (same prior) |\n\nThis means the EU-prompt study required only 1,500 new API calls (choices),\nnot the full ~3,150 of the base study.\n\n## Results {#sec-results}\n\n### Loading Posterior Draws\n\n::: {#load-posteriors .cell execution_count=2}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\nfrom report_utils import set_seu_style, SEU_COLORS, SEU_PALETTE\nset_seu_style()\n\ntemperatures = [0.0, 0.3, 0.7, 1.0, 1.5]\ntemp_labels = {t: f\"T={t}\" for t in temperatures}\n\ndef temp_key(t):\n    return f\"T{str(t).replace('.', '_')}\"\n\n# EU-prompt alpha draws\neu_draws = {}\nfor t in temperatures:\n    data = np.load(data_dir / f\"alpha_draws_{temp_key(t)}.npz\")\n    eu_draws[t] = data['alpha']\n\n# Base study alpha draws (from sibling report's frozen data)\nbase_data_dir = Path(\"..\") / \"temperature_study\" / \"data\"\nbase_draws = {}\nfor t in temperatures:\n    data = np.load(base_data_dir / f\"alpha_draws_{temp_key(t)}.npz\")\n    base_draws[t] = data['alpha']\n\n# Pre-computed cross-study analysis\nwith open(data_dir / \"cross_study_analysis.json\") as f:\n    cross = json.load(f)\n\n# Fit summaries\nwith open(data_dir / \"fit_summary.json\") as f:\n    eu_fit = json.load(f)\n\nwith open(base_data_dir / \"fit_summary.json\") as f:\n    base_fit = json.load(f)\n```\n:::\n\n\n::: {#28fe38bc .cell execution_count=3}\n\n::: {.cell-output .cell-output-stdout}\n```\n  T=0.0: 4,000 posterior draws loaded (EU-prompt)\n  T=0.3: 4,000 posterior draws loaded (EU-prompt)\n  T=0.7: 4,000 posterior draws loaded (EU-prompt)\n  T=1.0: 4,000 posterior draws loaded (EU-prompt)\n  T=1.5: 4,000 posterior draws loaded (EU-prompt)\n```\n:::\n:::\n\n\n### MCMC Diagnostics\n\n::: {#tbl-diagnostics .cell tbl-cap='MCMC diagnostics for all five temperature conditions under the EU-prompt. All fits used 4 chains with 1,000 warmup and 1,000 sampling iterations each (4,000 post-warmup draws total).' execution_count=4}\n``` {.python .cell-code}\nimport pandas as pd\nimport re\n\ndiag_rows = []\nfor t in temperatures:\n    with open(data_dir / f\"diagnostics_{temp_key(t)}.txt\") as f:\n        diag_text = f.read()\n\n    if \"No divergent transitions\" in diag_text or \"0 of\" in diag_text:\n        n_div = 0\n    else:\n        match = re.search(r'(\\d+) of (\\d+)', diag_text)\n        n_div = int(match.group(1)) if match else 0\n\n    rhat_ok = \"R-hat values satisfactory\" in diag_text or \"split R-hat values satisfactory\" in diag_text\n    ess_ok = \"effective sample size satisfactory\" in diag_text\n    ebfmi_ok = \"E-BFMI satisfactory\" in diag_text\n\n    diag_rows.append({\n        'Temperature': t,\n        'Divergences': f\"{n_div}/4000\",\n        'R̂': '✓' if rhat_ok else '✗',\n        'ESS': '✓' if ess_ok else '✗',\n        'E-BFMI': '✓' if ebfmi_ok else '✗',\n    })\n\npd.DataFrame(diag_rows)\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Temperature</th>\n      <th>Divergences</th>\n      <th>R̂</th>\n      <th>ESS</th>\n      <th>E-BFMI</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0.0</td>\n      <td>2/4000</td>\n      <td>✓</td>\n      <td>✓</td>\n      <td>✓</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>0.3</td>\n      <td>0/4000</td>\n      <td>✓</td>\n      <td>✓</td>\n      <td>✓</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>0.7</td>\n      <td>1/4000</td>\n      <td>✗</td>\n      <td>✓</td>\n      <td>✓</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1.0</td>\n      <td>0/4000</td>\n      <td>✓</td>\n      <td>✓</td>\n      <td>✓</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1.5</td>\n      <td>1/4000</td>\n      <td>✓</td>\n      <td>✓</td>\n      <td>✓</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Posterior Summaries\n\n::: {#tbl-posteriors .cell tbl-cap='Posterior summaries for the sensitivity parameter α at each temperature level under the EU-prompt. Intervals are 90% credible intervals.' execution_count=5}\n``` {.python .cell-code}\nrows = []\nfor t in temperatures:\n    s = cross['per_temperature'][str(t)]\n    rows.append({\n        'Temperature': t,\n        'Median': f\"{s['eu_median']:.1f}\",\n        'Mean': f\"{s['eu_mean']:.1f}\",\n        'SD': f\"{eu_fit[str(t)]['alpha_sd']:.1f}\",\n        '90% CI': f\"[{s['eu_q05']:.1f}, {s['eu_q95']:.1f}]\",\n    })\n\npd.DataFrame(rows)\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Temperature</th>\n      <th>Median</th>\n      <th>Mean</th>\n      <th>SD</th>\n      <th>90% CI</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0.0</td>\n      <td>57.0</td>\n      <td>59.6</td>\n      <td>16.0</td>\n      <td>[38.6, 89.7]</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>0.3</td>\n      <td>52.8</td>\n      <td>54.9</td>\n      <td>15.4</td>\n      <td>[34.1, 83.6]</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>0.7</td>\n      <td>54.7</td>\n      <td>56.9</td>\n      <td>14.2</td>\n      <td>[38.3, 83.3]</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1.0</td>\n      <td>43.3</td>\n      <td>44.7</td>\n      <td>10.5</td>\n      <td>[30.4, 64.2]</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1.5</td>\n      <td>26.3</td>\n      <td>27.1</td>\n      <td>5.9</td>\n      <td>[18.9, 37.9]</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe EU-prompt estimates show the same qualitative pattern as the base study: $\\alpha$ is highest at $T = 0.0$ and declines with increasing temperature. The near-equality of $T = 0.3$ and $T = 0.7$ also persists.\n\n### Forest Plot\n\n::: {#cell-fig-forest-eu .cell fig-height='5' execution_count=6}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(8, 5))\n\ny_positions = np.arange(len(temperatures))[::-1]\n\nfor i, t in enumerate(temperatures):\n    draws = eu_draws[t]\n    median = np.median(draws)\n    q05, q25, q75, q95 = np.percentile(draws, [5, 25, 75, 95])\n\n    y = y_positions[i]\n    ax.plot([q05, q95], [y, y], color=SEU_PALETTE[i], linewidth=1.5, alpha=0.7)\n    ax.plot([q25, q75], [y, y], color=SEU_PALETTE[i], linewidth=4, alpha=0.9)\n    ax.plot(median, y, 'o', color=SEU_PALETTE[i], markersize=8,\n            markeredgecolor='white', markeredgewidth=1.5, zorder=5)\n\nax.set_yticks(y_positions)\nax.set_yticklabels([f'T = {t}' for t in temperatures])\nax.set_xlabel('Sensitivity (α)')\nax.set_title('EU-Prompt: Posterior Distributions of α by Temperature')\nax.grid(axis='x', alpha=0.3)\nax.grid(axis='y', alpha=0)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Forest plot of posterior α distributions under the EU-prompt. Points show posterior medians; thick bars span the 50% credible interval; thin bars span the 90% credible interval.](01_eu_prompt_study_files/figure-html/fig-forest-eu-output-1.svg){#fig-forest-eu}\n:::\n:::\n\n\n### Posterior Densities\n\n::: {#cell-fig-density-eu .cell fig-height='5' execution_count=7}\n``` {.python .cell-code}\nfrom scipy.stats import gaussian_kde\n\nfig, ax = plt.subplots(figsize=(8, 5))\n\nfor i, t in enumerate(temperatures):\n    draws = eu_draws[t]\n    kde = gaussian_kde(draws)\n    x_grid = np.linspace(draws.min() * 0.8, draws.max() * 1.1, 300)\n    ax.fill_between(x_grid, kde(x_grid), alpha=0.2, color=SEU_PALETTE[i])\n    ax.plot(x_grid, kde(x_grid), color=SEU_PALETTE[i], linewidth=2,\n            label=f'T = {t} (median = {np.median(draws):.0f})')\n\nax.set_xlabel('Sensitivity (α)')\nax.set_ylabel('Density')\nax.set_title('EU-Prompt: Posterior Density of α')\nax.legend(loc='upper right')\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Kernel density estimates of the posterior α distributions under the EU-prompt.](01_eu_prompt_study_files/figure-html/fig-density-eu-output-1.svg){#fig-density-eu}\n:::\n:::\n\n\n### Posterior Predictive Checks\n\n::: {#tbl-ppc .cell tbl-cap='Posterior predictive check p-values for each temperature condition under the EU-prompt. Values near 0.5 indicate good calibration.' execution_count=8}\n``` {.python .cell-code}\nppc_rows = []\nfor t in temperatures:\n    with open(data_dir / f\"ppc_{temp_key(t)}.json\") as f:\n        ppc = json.load(f)\n\n    pvals = ppc['p_values']\n    ppc_rows.append({\n        'Temperature': t,\n        'Log-likelihood': f\"{pvals['ll']:.3f}\",\n        'Modal frequency': f\"{pvals['modal']:.3f}\",\n        'Mean probability': f\"{pvals['prob']:.3f}\",\n    })\n\npd.DataFrame(ppc_rows)\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Temperature</th>\n      <th>Log-likelihood</th>\n      <th>Modal frequency</th>\n      <th>Mean probability</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0.0</td>\n      <td>0.432</td>\n      <td>0.456</td>\n      <td>0.423</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>0.3</td>\n      <td>0.438</td>\n      <td>0.670</td>\n      <td>0.531</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>0.7</td>\n      <td>0.453</td>\n      <td>0.544</td>\n      <td>0.498</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1.0</td>\n      <td>0.452</td>\n      <td>0.490</td>\n      <td>0.476</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1.5</td>\n      <td>0.494</td>\n      <td>0.567</td>\n      <td>0.506</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nAll PPC p-values fall within $[0.42, 0.67]$, indicating adequate model fit at every temperature level. The m_01 model describes the EU-prompt choice data as well as it describes the base study data.\n\n## Cross-Study Comparison {#sec-comparison}\n\nThe central question is whether explicit EU-maximization instructions increase or decrease estimated sensitivity. We compare the two studies using the same 4,000 posterior draws per condition.\n\n### Per-Temperature Comparison\n\n::: {#tbl-cross-study .cell tbl-cap='Per-temperature comparison of α estimates. P(base > EU) is the posterior probability that the base study\\'s α exceeds the EU-prompt study\\'s α at a given temperature.' execution_count=9}\n``` {.python .cell-code}\nrows = []\nfor t in temperatures:\n    s = cross['per_temperature'][str(t)]\n    rows.append({\n        'Temperature': t,\n        'Base α (median)': f\"{s['base_median']:.1f}\",\n        'EU α (median)': f\"{s['eu_median']:.1f}\",\n        'Δ (base − EU)': f\"{s['diff_median']:+.1f}\",\n        'P(base > EU)': f\"{s['p_base_gt_eu']:.3f}\",\n    })\n\npd.DataFrame(rows)\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Temperature</th>\n      <th>Base α (median)</th>\n      <th>EU α (median)</th>\n      <th>Δ (base − EU)</th>\n      <th>P(base &gt; EU)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0.0</td>\n      <td>74.1</td>\n      <td>57.0</td>\n      <td>+16.9</td>\n      <td>0.750</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>0.3</td>\n      <td>54.9</td>\n      <td>52.8</td>\n      <td>+2.2</td>\n      <td>0.544</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>0.7</td>\n      <td>56.3</td>\n      <td>54.7</td>\n      <td>+1.4</td>\n      <td>0.532</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1.0</td>\n      <td>39.1</td>\n      <td>43.3</td>\n      <td>-4.3</td>\n      <td>0.365</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1.5</td>\n      <td>36.0</td>\n      <td>26.3</td>\n      <td>+9.7</td>\n      <td>0.848</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe EU-prompt *lowers* estimated $\\alpha$ at three of five temperatures (0.0, 0.3, 0.7), raises it slightly at $T = 1.0$, and lowers it substantially at $T = 1.5$. However, the 90% credible intervals on $\\alpha_{\\text{base}} - \\alpha_{\\text{EU}}$ contain zero at every temperature—the individual per-temperature differences are not decisive.\n\n### Overlaid Posterior Densities\n\n::: {#cell-fig-overlay .cell fig-height='10' execution_count=10}\n``` {.python .cell-code}\nfig, axes = plt.subplots(5, 1, figsize=(8, 10), sharex=True)\n\nfor i, t in enumerate(temperatures):\n    ax = axes[i]\n    base = base_draws[t]\n    eu = eu_draws[t]\n\n    x_lo = min(base.min(), eu.min()) * 0.8\n    x_hi = max(base.max(), eu.max()) * 1.1\n    x_grid = np.linspace(x_lo, x_hi, 300)\n\n    kde_base = gaussian_kde(base)\n    kde_eu = gaussian_kde(eu)\n\n    ax.fill_between(x_grid, kde_base(x_grid), alpha=0.2, color=SEU_COLORS['primary'])\n    ax.plot(x_grid, kde_base(x_grid), color=SEU_COLORS['primary'], linewidth=2,\n            label=f'Base (median={np.median(base):.0f})')\n\n    ax.fill_between(x_grid, kde_eu(x_grid), alpha=0.2, color=SEU_COLORS['accent'])\n    ax.plot(x_grid, kde_eu(x_grid), color=SEU_COLORS['accent'], linewidth=2,\n            linestyle='--', label=f'EU-prompt (median={np.median(eu):.0f})')\n\n    s = cross['per_temperature'][str(t)]\n    ax.set_title(f'T = {t}    |    P(base > EU) = {s[\"p_base_gt_eu\"]:.3f}', fontsize=11)\n    ax.legend(fontsize=9)\n    ax.set_ylabel('Density')\n    ax.grid(True, alpha=0.2)\n\naxes[-1].set_xlabel('Sensitivity (α)')\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Overlaid posterior densities of α for the base study (solid) and EU-prompt study (dashed) at each temperature. Shading highlights the region where the base study's posterior exceeds the EU-prompt study's.](01_eu_prompt_study_files/figure-html/fig-overlay-output-1.svg){#fig-overlay}\n:::\n:::\n\n\nThe overlaid densities show substantial overlap at every temperature. The most visible separation occurs at $T = 0.0$ (where the base study's median is $\\sim$17 points higher) and $T = 1.5$ (where the gap is $\\sim$10 points). At the middle temperatures, the two posteriors are nearly indistinguishable.\n\n### Summary Plot\n\n::: {#cell-fig-comparison-summary .cell fig-height='5' execution_count=11}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(13, 5))\n\n# Left: medians with CIs\nax = axes[0]\noffset = 0.02\nfor label, draws, color, shift in [\n    ('Base', base_draws, SEU_COLORS['primary'], -offset),\n    ('EU-prompt', eu_draws, SEU_COLORS['accent'], offset),\n]:\n    medians = [np.median(draws[t]) for t in temperatures]\n    q05s = [np.percentile(draws[t], 5) for t in temperatures]\n    q95s = [np.percentile(draws[t], 95) for t in temperatures]\n    x = np.array(temperatures) + shift\n    ax.errorbar(x, medians,\n                yerr=[np.array(medians) - np.array(q05s),\n                      np.array(q95s) - np.array(medians)],\n                fmt='o-', color=color, linewidth=2, markersize=7,\n                capsize=5, capthick=1.5, label=label)\n\nax.set_xlabel('Temperature')\nax.set_ylabel('Sensitivity (α)')\nax.set_title('α vs. Temperature: Base vs. EU-Prompt')\nax.set_xticks(temperatures)\nax.legend()\nax.grid(True, alpha=0.3)\n\n# Right: posterior of the difference\nax = axes[1]\nn_draws = cross['n_draws']\nfor i, t in enumerate(temperatures):\n    diff = base_draws[t][:n_draws] - eu_draws[t][:n_draws]\n    parts = ax.violinplot([diff], positions=[i], showmedians=True, showextrema=False)\n    for pc in parts['bodies']:\n        pc.set_facecolor(SEU_PALETTE[i])\n        pc.set_alpha(0.5)\n    parts['cmedians'].set_color(SEU_PALETTE[i])\n\nax.axhline(0, color='gray', linestyle='--', alpha=0.5, label='No difference')\nax.set_xticks(range(len(temperatures)))\nax.set_xticklabels([f'{t}' for t in temperatures])\nax.set_xlabel('Temperature')\nax.set_ylabel('α_base − α_EU')\nax.set_title('Posterior of the Prompt Effect (Δα)')\nax.legend()\nax.grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Left: posterior medians with 90% credible intervals for both studies. Right: posterior distribution of α_base − α_EU at each temperature (positive = EU-prompt yields lower α).](01_eu_prompt_study_files/figure-html/fig-comparison-summary-output-1.svg){#fig-comparison-summary}\n:::\n:::\n\n\n### Slope Comparison\n\nThe [initial study](../temperature_study/01_initial_study.qmd) estimated a global slope of $\\Delta\\alpha / \\Delta T \\approx -25$ (90% CI $[-52, -7]$). We now compare the draw-wise slope from both studies:\n\n::: {#cell-fig-slope-comparison .cell execution_count=12}\n``` {.python .cell-code}\nsc = cross['slope_comparison']\n\ntemp_array = np.array(temperatures)\nt_var = np.var(temp_array)\n\nbase_slopes = []\neu_slopes = []\nfor i in range(cross['n_draws']):\n    ba = np.array([base_draws[t][i] for t in temperatures])\n    ea = np.array([eu_draws[t][i] for t in temperatures])\n    base_slopes.append(np.cov(temp_array, ba)[0, 1] / t_var)\n    eu_slopes.append(np.cov(temp_array, ea)[0, 1] / t_var)\n\nbase_slopes = np.array(base_slopes)\neu_slopes = np.array(eu_slopes)\n\nfig, ax = plt.subplots(figsize=(8, 4))\n\nfor slopes, label, color, ls in [\n    (base_slopes, 'Base', SEU_COLORS['primary'], '-'),\n    (eu_slopes, 'EU-prompt', SEU_COLORS['accent'], '--'),\n]:\n    kde = gaussian_kde(slopes)\n    x_grid = np.linspace(np.percentile(slopes, 0.5), np.percentile(slopes, 99.5), 300)\n    ax.fill_between(x_grid, kde(x_grid), alpha=0.2, color=color)\n    ax.plot(x_grid, kde(x_grid), color=color, linewidth=2, linestyle=ls,\n            label=f'{label} (median = {np.median(slopes):.1f})')\n\nax.axvline(0, color='gray', linestyle='--', alpha=0.5)\nax.set_xlabel('Slope (Δα / ΔT)')\nax.set_ylabel('Density')\nax.set_title('Temperature–Sensitivity Slope: Base vs. EU-Prompt')\nax.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Posterior distributions of the temperature–sensitivity slope (Δα/ΔT) for the base study and EU-prompt study. Both slopes are clearly negative; their distributions overlap substantially.](01_eu_prompt_study_files/figure-html/fig-slope-comparison-output-1.svg){#fig-slope-comparison}\n:::\n:::\n\n\n::: {#6f4ad8d7 .cell execution_count=13}\n\n::: {.cell-output .cell-output-stdout}\n```\nBase slope:  median = -30.8,  90% CI [-65.5, -8.3]\nEU slope:    median = -24.7,  90% CI [-48.6, -7.0]\nP(EU slope steeper than base): 0.390\n```\n:::\n:::\n\n\nBoth slopes are clearly negative, confirming that the monotone temperature effect is preserved under the EU-prompt. The EU-prompt slope is slightly shallower (median $\\approx -25$ vs $-31$), but the difference is not credible—$P(\\text{EU slope steeper}) \\approx 0.39$, far from decisive.\n\n### Monotonicity\n\n::: {#3c93a982 .cell execution_count=14}\n``` {.python .cell-code}\nm = cross['monotonicity']\nprint(f\"P(strict monotonicity):\")\nprint(f\"  Base:      {m['base_strict_monotonicity']:.3f}\")\nprint(f\"  EU-prompt: {m['eu_strict_monotonicity']:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nP(strict monotonicity):\n  Base:      0.125\n  EU-prompt: 0.087\n```\n:::\n:::\n\n\nStrict monotonicity probabilities are comparable and modest in both cases, driven by the $T = 0.3 \\approx T = 0.7$ plateau that persists across prompt conditions.\n\n## Discussion {#sec-discussion}\n\n### Summary of Findings\n\nThe EU-prompt study yields three main findings:\n\n1. **The temperature–sensitivity gradient is preserved.** Explicit EU-maximization instructions do not disrupt the monotone relationship between temperature and $\\alpha$. The global slope, pairwise ordering, and approximate magnitude are reproduced.\n\n2. **The EU-prompt does not increase α.** Contrary to the naive expectation that telling the LLM to maximize expected utility would make its choices more EU-aligned, the point estimates of $\\alpha$ are *lower* under the EU-prompt at four of five temperatures. The effect is most visible at $T = 0.0$ ($\\Delta \\approx -17$) and $T = 1.5$ ($\\Delta \\approx -10$).\n\n3. **The per-temperature differences are not individually decisive.** The 90% credible intervals on $\\alpha_{\\text{base}} - \\alpha_{\\text{EU}}$ contain zero at every temperature, and no single $P(\\text{base} > \\text{EU})$ exceeds 0.85. This is a pattern-level finding, not a temperature-specific one.\n\n::: {#cell-fig-summary .cell execution_count=15}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(6, 1.5))\n\nprobs = [cross['per_temperature'][str(t)]['p_base_gt_eu'] for t in temperatures]\nprobs_arr = np.array(probs).reshape(1, -1)\n\nim = ax.imshow(probs_arr, cmap='RdYlGn', vmin=0.2, vmax=0.8, aspect='auto')\nax.set_xticks(range(len(temperatures)))\nax.set_xticklabels([f'{t}' for t in temperatures])\nax.set_yticks([])\nax.set_xlabel('Temperature')\n\nfor j, p in enumerate(probs):\n    color = 'white' if p > 0.7 or p < 0.3 else 'black'\n    ax.text(j, 0, f'{p:.2f}', ha='center', va='center', fontsize=11, fontweight='bold',\n            color=color)\n\nplt.colorbar(im, ax=ax, shrink=0.8, label='P(α_base > α_EU)')\nax.set_title('P(base > EU) by Temperature')\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Summary heatmap of P(α_base > α_EU) at each temperature. Values above 0.5 indicate the base study yields higher sensitivity. The pattern is consistent at 4/5 temperatures, with T=1.0 as the exception.](01_eu_prompt_study_files/figure-html/fig-summary-output-1.svg){#fig-summary}\n:::\n:::\n\n\n### Why Might Explicit EU Instructions Reduce Sensitivity?\n\nThe finding that explicit EU-maximization instructions *decrease* rather than increase estimated $\\alpha$ admits several interpretations. We consider three, ordered from most to least favorable to the LLM.\n\n**1. Prompt interference with implicit competence.** The base study's high $\\alpha$ values (median $\\approx 74$ at $T = 0.0$) suggest that GPT-4o already approximates EU-maximizing behavior without being told to do so. The model's training on vast corpora of human decision-making text has likely instilled robust decision heuristics that, in this task domain, produce choices closely aligned with EU maximization. Adding explicit EU instructions may *interfere* with these heuristics by forcing the model into a more deliberate reasoning mode. This is analogous to the well-documented finding in cognitive science that conscious rule-following can degrade the performance of automatic, well-practiced skills.\n\n**2. Imperfect explicit calculation.** The EU-prompt asks the model to \"consider the subjective probability you assign to each outcome and your utility for that outcome\" and \"choose the claim for which the probability-weighted utility across the three outcomes is highest.\" This invites the model to perform an explicit numerical computation—assigning probabilities, utilities, multiplying, and summing. If the model performs this computation imprecisely (e.g., miscalibrated probabilities, crude utility estimates), the resulting choices could be *less* EU-aligned than those produced by the model's default, holistic assessment of the claims. The explicit framework may be correct in principle but implemented poorly in the model's token-by-token generation process.\n\n**3. Frame narrowing.** The EU-prompt constrains the model's attention to a specific decision-theoretic framework. The base prompt, by contrast, leaves the decision criterion open—the model is free to draw on whatever internal reasoning best discriminates among claims. The EU-prompt may cause the model to attend less to features of the claims that are relevant to the choice (and captured in the embedding-derived $w$ vectors) and more to the abstract probability-utility calculus. If the model's implicit feature weighting is better calibrated than its explicit probability × utility computation, the narrower frame reduces sensitivity.\n\nThese interpretations are not mutually exclusive. All three point to a common theme: **the gap between competence and articulable reasoning.** The model appears to \"know\" how to choose well but cannot reliably improve its choices when asked to explain or formalize its decision process.\n\n### Implications for the Sensitivity Framework\n\nThe finding has a natural interpretation within the SEU sensitivity framework developed in the [foundational reports](../../foundations/01_abstract_formulation.qmd):\n\n- The sensitivity parameter $\\alpha$ captures how sharply choices track expected utility differences. A high $\\alpha$ does not require the agent to perform explicit EU calculations—it only requires that the agent's choices are *as if* it were maximizing EU with some noise.\n\n- The EU-prompt intervention targets the *articulable commitment* to EU maximization without necessarily improving the *performance*. In the commitment–performance distinction of Report 1, the prompt modifies the commitment framing but may degrade performance by disrupting well-functioning implicit processes.\n\n- This result is consistent with the view that $\\alpha$ measures a *behavioral* property of the agent—the degree to which its choices covary with EU rankings—rather than a *cognitive* property (whether the agent explicitly represents probabilities and utilities). An agent can have high $\\alpha$ without any explicit EU reasoning, and explicit EU reasoning can coexist with lower $\\alpha$.\n\n### The T = 1.0 Exception\n\nAt $T = 1.0$, the EU-prompt yields slightly *higher* $\\alpha$ than the base study (median 43.3 vs 39.1, $P(\\text{base} > \\text{EU}) = 0.37$). While this is not statistically decisive, it is the only temperature where the direction reverses. One speculative explanation: at moderate-to-high temperature, the base model's implicit heuristics may be sufficiently disrupted by sampling noise that the explicit EU framework provides some anchoring benefit. This would predict a U-shaped interaction where the EU-prompt hurts at low temperatures (where implicit competence is high) and helps at higher temperatures (where implicit competence is degraded). The current data are insufficient to test this conjecture—it would require additional temperature levels in the moderate-to-high range.\n\n### Limitations\n\nThis study has several limitations that constrain the strength of its conclusions:\n\n1. **Independent posteriors.** The base and EU-prompt $\\alpha$ values are estimated from *independent* model fits—there is no joint posterior over (α_base, α_EU). The posterior probabilities $P(\\alpha_{\\text{base}} > \\alpha_{\\text{EU}})$ are computed from draws matched by index, which is valid only insofar as MCMC mixing is adequate (which diagnostics confirm). A joint model that shares structure across prompt conditions would provide sharper inference.\n\n2. **Single model, single task.** All conclusions are conditional on the m_01 model, the insurance triage task, and GPT-4o. The EU-prompt effect may differ with other model specifications, task domains, or LLM architectures.\n\n3. **Prompt specificity.** The EU-prompt uses one particular formulation of the EU-maximization instruction. Alternative phrasings—more or less detailed, referencing specific numerical formats, or using chain-of-thought scaffolding—could produce different results.\n\n4. **No assessment variation.** By design, assessments are reused from the base study. The EU-prompt modifies only the choice prompt. If the instruction to maximize EU also affected how the model *assesses* claims (which it might, via priming effects on the assessment prompt), then the current design underestimates the full impact of the EU-maximization framing.\n\n## Reproducibility {#sec-reproducibility}\n\n### Data Snapshot\n\nAll results are loaded from a frozen data snapshot in the `data/` subdirectory. This snapshot is version-controlled and immune to future pipeline re-runs.\n\n| File | Description |\n|------|-------------|\n| `alpha_draws_T*.npz` | Posterior draws of α (4,000 per condition) |\n| `ppc_T*.json` | Posterior predictive check results |\n| `diagnostics_T*.txt` | CmdStan diagnostic output |\n| `stan_data_T*.json` | Stan-ready data (for refitting) |\n| `fit_summary.json` | Summary statistics across conditions |\n| `cross_study_analysis.json` | Pre-computed comparison with the base study |\n| `run_summary.json` | Pipeline metadata and configuration |\n| `study_config.yaml` | Frozen copy of the study configuration |\n| `prompts.yaml` | Frozen copy of the EU-prompt templates |\n\n### Running the Study\n\n```bash\n# Validate configuration and base study data availability\npython -m applications.temperature_study_with_eu_prompt validate\n\n# Estimate API costs (choices only)\npython -m applications.temperature_study_with_eu_prompt estimate-cost\n\n# Run choice collection (skip model fitting for now)\npython -m applications.temperature_study_with_eu_prompt run --skip-fitting\n\n# Fit models on collected data\npython -m applications.temperature_study_with_eu_prompt fit\n\n# Freeze data snapshot for this report\npython scripts/freeze_eu_prompt_report_data.py\n```\n\n## Next Steps\n\n1. **Joint hierarchical model.** A model that includes prompt condition as a covariate would provide direct inference on the EU-prompt effect and its interaction with temperature, without relying on independent posterior comparisons.\n\n2. **Alternative EU-prompt formulations.** Testing whether the sensitivity-reducing effect is robust to different wordings of the EU-maximization instruction, including chain-of-thought variants that ask the model to show its probability and utility estimates before choosing.\n\n3. **Assessment-level intervention.** Extending the EU-prompt to the assessment phase (where the model evaluates individual claims) would test whether the EU framing affects belief formation, not only the decision rule.\n\n4. **Cross-architecture replication.** Repeating with a different LLM (e.g., Claude) would test whether the prompt interference effect is specific to GPT-4o's architecture or reflects a more general phenomenon.\n\n## References\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "01_eu_prompt_study_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}