"""Reproduce the October display/tie supplement without altering the snapshot."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
from statistics import NormalDist

import numpy as np
import yaml

from applications.seu_sensitivity_study.assessment_scale import TIE_ATOL
from applications.seu_sensitivity_study.data_preparation import assessment_expected_utilities


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "reports/applications/seu_sensitivity_study"
BUNDLE = REPORT / "data/design_evidence.yml"
OUTPUT = REPORT / "data/display_evidence.json"
INCLUDE = REPORT / "_display_evidence.qmd"


def summarize_gaps(gaps):
    values = np.asarray(gaps, dtype=float)
    if values.ndim != 1 or not len(values) or not np.all(np.isfinite(values)) or np.any(values < 0):
        raise ValueError("Expected nonempty finite nonnegative top-two gaps")
    exact = int(np.count_nonzero(values == 0))
    near = int(np.count_nonzero(np.isclose(values, 0, atol=TIE_ATOL, rtol=0)))
    return {"menu_count": len(values), "exact_ties": exact,
            "additional_near_ties": near - exact, "ties_with_tolerance": near,
            "tie_prevalence": near / len(values)}


def build_evidence(bundle):
    rows = []
    for pool_id, matched_family in (("venture", "procurement"), ("hiring", "matched")):
        pool = bundle["pools"][pool_id]
        if len(pool["items"]) != 60 or len(pool["probabilities"]) != 6:
            raise ValueError("Expected 60 items and six arms per pool")
        item_ids = [item["id"] for item in pool["items"]]
        for family, expected_count in ((None, 140), (matched_family, 40)):
            menus = [menu for menu in pool["menus"] if family is None or menu["family"] == family]
            if len(menus) != expected_count or len({menu["id"] for menu in menus}) != expected_count:
                raise ValueError("Expected the complete fixed menu set with unique IDs")
            for model, probabilities in pool["probabilities"].items():
                eta = dict(zip(item_ids, assessment_expected_utilities(
                    probabilities, item_ids=item_ids, utilities=[0.0, 0.5, 1.0])))
                gaps = []
                for menu in menus:
                    ordered = sorted(eta[item_id] for item_id in menu["item_ids"])
                    gaps.append(float(ordered[-1] - ordered[-2]))
                rows.append({"pool": pool_id, "family": family or "all", "model": model,
                             "menu_ids": [menu["id"] for menu in menus], "top_two_gaps": gaps,
                             **summarize_gaps(gaps)})
    sources = [BUNDLE, Path(__file__),
               ROOT / "applications/seu_sensitivity_study/assessment_scale.py",
               ROOT / "applications/seu_sensitivity_study/data_preparation.py"]
    return {
        "schema_version": 1, "date": "2026-10-07", "utility_midpoint": 0.5,
        "tie_atol": TIE_ATOL, "tie_rtol": 0.0,
        "eta_arithmetic": "assessment_expected_utilities; normalize probabilities before computing eta",
        "menu_weighting": "one per frozen menu ID, not per presentation; repeated compositions retained",
        "choice_records_read": False, "posterior_fits": 0, "provider_calls": 0,
        "size_ratio_prior_central_90": [math.exp(6 * 0.2 * NormalDist().inv_cdf(probability))
                                        for probability in (0.05, 0.95)],
        "source_hashes": {str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest()
                          for path in sources},
        "rows": rows,
    }


def render_include(evidence):
    lines = [
        "<!-- Generated by python -m analysis.study_display_evidence --write. -->",
        "### October Display and Tie Reconciliation {#sec-display-ties}",
        "",
        "This October 7 supplement uses the frozen September probability/menu bundle, not production choices. "
        "The table counts menus whose two largest expected utilities coincide exactly, followed by additional "
        "menus whose positive gap is at most $10^{-12}$ (relative tolerance zero). "
        "The last column includes both categories. Counts are descriptive geometry, not observed maximizing rates. "
        "A top-two tie need not make every alternative equally valued.",
        "",
        "Primary-pool rows count all 140 menu IDs, including the 40 matched-family menus. "
        "Matched rows show those 40-menu subsets separately, so they are not independent additional menus. "
        "Each ID counts once, not once per presentation; repeated compositions with distinct IDs are retained. "
        "All arms use their own neutral assessments and utilities $(0,0.5,1)$. "
        "Expected utilities use the current canonical probability-normalization helper; no display rounding "
        "enters the calculation. The historical figure retains its original arithmetic and is not overwritten.",
        "",
        "| Pool / subset | Arm | Exact ties | Additional near ties | All ties within tolerance |",
        "|---|---|---:|---:|---:|",
    ]
    for row in evidence["rows"]:
        count = row["menu_count"]
        lines.append(f"| {row['pool']} / {row['family']} | {row['model']} | "
                     f"{row['exact_ties']}/{count} | {row['additional_near_ties']}/{count} | "
                     f"{row['ties_with_tolerance']}/{count} ({100 * row['tie_prevalence']:.1f}%) |")
    lines.extend([
        "",
        "Neutral-probability cells in the report's example tables display six decimal places. "
        "Verbatim request blocks and the downloadable historical YAML retain their original values, "
        "including floating-point representation artifacts. Equal displayed values therefore do not "
        "establish exact equality in the calculation. This formatting does not change assessment "
        "probabilities, likelihood inputs, or the predictive checks' exact-maximizer rule.",
        "",
        "The [machine-readable supplement](data/display_evidence.json) retains menu IDs, unrounded "
        "top-two gaps, the analytic size-prior interval and source hashes. Reproduce it with "
        "`python -m analysis.study_display_evidence --check`. The September exporter and its outputs "
        "are unchanged; this is a separately dated supplement.",
    ])
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    evidence = build_evidence(yaml.safe_load(BUNDLE.read_text()))
    serialized = json.dumps(evidence, indent=2, sort_keys=True, allow_nan=False) + "\n"
    rendered = render_include(evidence)
    if args.write:
        OUTPUT.write_text(serialized)
        INCLUDE.write_text(rendered)
    if OUTPUT.read_text() != serialized or INCLUDE.read_text() != rendered:
        raise ValueError("Display evidence differs from recomputed frozen-input results")
    print("Display evidence validated: 24 arm/subset rows; historical bundle unchanged.")


if __name__ == "__main__":
    main()